# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
    # -   id: nbqa-black
    -   id: nbqa-flake8
    -   id: nbqa-autopep8
    -   id: nbqa-isort
